"""API Models."""
from .requests import (
    ChatRequest,
    ChatHistoryRequest,
    IngestTextRequest,
    IngestURLRequest,
    CreateCollectionRequest,
    DeleteCollectionRequest,
    EvaluateRequest,
)
from .responses import (
    Source,
    HealthResponse,
    ChatResponse,
    ChatMessage,
    ChatHistoryResponse,
    StreamToken,
    StreamSources,
    StreamDone,
    StreamError,
    IngestResponse,
    IngestStatusResponse,
    CollectionInfo,
    CollectionListResponse,
    CollectionDocumentsResponse,
    RAGASMetrics,
    EvaluateResponse,
    ErrorResponse,
    # Chat Documents
    ChatDocument,
    DocumentUploadResult,
    DocumentUploadFailed,
    DocumentUploadResponse,
    DocumentListResponse,
    DocumentDeleteResponse,
    ChatDeleteResponse,
    DocumentPreviewResponse,
)

__all__ = [
    # Requests
    "ChatRequest",
    "ChatHistoryRequest",
    "IngestTextRequest",
    "IngestURLRequest",
    "CreateCollectionRequest",
    "DeleteCollectionRequest",
    "EvaluateRequest",
    # Responses
    "Source",
    "HealthResponse",
    "ChatResponse",
    "ChatMessage",
    "ChatHistoryResponse",
    "StreamToken",
    "StreamSources",
    "StreamDone",
    "StreamError",
    "IngestResponse",
    "IngestStatusResponse",
    "CollectionInfo",
    "CollectionListResponse",
    "CollectionDocumentsResponse",
    "RAGASMetrics",
    "EvaluateResponse",
    "ErrorResponse",
    # Chat Documents
    "ChatDocument",
    "DocumentUploadResult",
    "DocumentUploadFailed",
    "DocumentUploadResponse",
    "DocumentListResponse",
    "DocumentDeleteResponse",
    "ChatDeleteResponse",
    "DocumentPreviewResponse",
]
